name: Compress & Resize Images
on:
  pull_request:
    # Run Image Actions when pull request to master branch.
    # See https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#onpushpull_requestpaths for reference.
    branches:
      - master

jobs:
  build:
    # Only run on Pull Requests within the same repository, and not from forks.
    if: github.event.pull_request.head.repo.full_name == github.repository
    name: calibreapp/image-actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      # Resize images
      - name: Image Resize to 400x
        uses: sharadcodes/img-resizer@v1.1
        with:
          image-folder: 'assets/img/master' # This has original images
          new-resolution: '400x' # default is 400x
          output-folder: "assets/img/400"
      - name: Image Resize to 600x
        uses: sharadcodes/img-resizer@v1.1
        with:
          image-folder: 'assets/img/master' # This has original images
          new-resolution: '600x' # default is 400x
          output-folder: "assets/img/600"
      - name: Image Resizer to 800x
        uses: sharadcodes/img-resizer@v1.1
        with:
          image-folder: 'assets/img/master' # This has original images
          new-resolution: '800x' # default is 400x
          output-folder: "assets/img/800"
      - name: Image Resize to 1000x
        uses: sharadcodes/img-resizer@v1.1
        with:
          image-folder: 'assets/img/master' # This has original images
          new-resolution: '1000x' # default is 400x
          output-folder: "assets/img/1000"
      - name: Image Resize to 1160x
        uses: sharadcodes/img-resizer@v1.1
        with:
          image-folder: 'assets/img/master' # This has original images
          new-resolution: '1160x' # default is 400x
          output-folder: "assets/img/1160"
      - name: Compress Images
        uses: calibreapp/image-actions@main
        with:
          jpegQuality: '80'
          jpegProgressive: false
          pngQuality: '80'
          webpQuality: '80'
          # The `GITHUB_TOKEN` is automatically generated by GitHub and scoped only to the repository that is currently running the action. By default, the action canâ€™t update Pull Requests initiated from forked repositories.
          # See https://docs.github.com/en/actions/reference/authentication-in-a-workflow and https://help.github.com/en/articles/virtual-environments-for-github-actions#token-permissions
          githubToken: ${{ secrets.GITHUB_TOKEN }}
     
